env:
  JDK_DISTRO: temurin
  JDK_VERSION: 21
jobs:
  analyze_sources:
    name: Do we need to build the application?
    outputs:
      run_build: ${{ steps.filter.outputs.src }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install packages...
      run: sudo apt-get install sysvbanner
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v4
    - continue-on-error: true
      id: filter
      name: Look for changes in monitored locations
      uses: dorny/paths-filter@v3
      with:
        filters: "src:\n  - 'src/**/*.flex'\n  - 'src/**/*.java'\n  - 'src/**/*.properties'\n\
          \  - '*.gradle*'\n  - 'gradle.properties'\n"
    - continue-on-error: true
      name: WILL BUILD STEP BE RUN?
      run: 'found="NO"

        [[ ${{ steps.filter.outputs.src }} == ''true'' ]] && found="YES"

        echo "run_build=${found}" >> $GITHUB_OUTPUT

        echo -e "\n****************************************\n"

        banner "${found}"

        echo -e "****************************************"

        '
  build:
    if: needs.analyze_sources.outputs.run_build == 'true'
    name: Gradle builder
    needs: analyze_sources
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JDK_VERSION }} ${{ env.JDK_DISTRO }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JDK_DISTRO }}
        java-version: ${{ env.JDK_VERSION }}
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Build with Gradle
      run: 'chmod +x gradlew

        ./gradlew build -x checkstyleMain -x checkstyleTest

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Run SonarQube
      run: ([ -z $SONAR_TOKEN ] || [ -z $SONAR_HOST_URL ] || ./gradlew sonar)
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
