jobs:
  check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: z0al/dependent-issues@v1
      with:
        check_issues: off
        keywords: DEPENDS_ON, BLOCKED_BY
        label: dependent
name: Dependabot
on:
  repository_dispatch:
    types: trigger-ga___dependabot.yml
