jobs:
  markdown_lint:
    name: Markdown linter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v4
    - continue-on-error: true
      id: filter
      name: Look for changed doc related files...
      uses: dorny/paths-filter@v3
      with:
        filters: "docs:\n  - 'docs/**'\n  - '**/*.md'\n"
    - continue-on-error: true
      if: steps.filter.outputs.docs == 'true'
      name: Running markdown linter...
      uses: ruzickap/action-my-markdown-linter@v1
      with:
        config_file: .markdownlint.yaml
        exclude: LICENSE.md
name: MD Lint
on:
  repository_dispatch:
    types: trigger-ga___markdown.yml
